apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mysql.fullname" . }}-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.auth.rootPassword | quote }}
  MYSQL_DATABASE: {{ .Values.auth.database | quote }}
  MYSQL_USER: {{ .Values.auth.username | quote }}
  MYSQL_PASSWORD: {{ .Values.auth.password | quote }}