apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mysql.fullname" . }}
spec:
  serviceName: {{ .Values.service.name }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "mysql.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "mysql.fullname" . }}
    spec:
      containers:
        - name: mysql
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3306
          envFrom:
            - secretRef:
                name: {{ include "mysql.fullname" . }}-secret
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
            {{- if .Values.initdb.enabled }}
            - name: initdb
              mountPath: /docker-entrypoint-initdb.d
              readOnly: true
            {{- end }}
      {{- if .Values.initdb.enabled }}
      volumes:
        - name: initdb
          configMap:
            name: {{ include "mysql.fullname" . }}-initdb
      {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: mysql-data
      spec:
        accessModes:
{{ toYaml .Values.persistence.accessModes | indent 10 }}
        resources:
          requests:
            storage: {{ .Values.persistence.size | quote }}